
[System]
Ver=2.7
UpDate=2009/07/22
Name=生産管理システム

[DataBase]
;Server=TXDBSVR
;Server=DL120
Server=10.201.2.2\SIM
Name=SIMTOKIDB
User=sa
BackDel=10
SqlAgent=
Name2=SIMPRA_K
Name3=SIMPRA_SG
Name4=SIMPRA_T
PASS=cisdb036

[MenuText]
FMV-E630=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP-DC7900=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
FMVW5220=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
FMV-D5255-PC=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
FMV-W5240U=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP78YY=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP-DX7500=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
FMV-W5240=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
FMV-W5210=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP780_KK=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP-6000P=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
FMV-D5340=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP_780_KK7=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP-7800Y7=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
YM-VPCXP02=Z:\SIMPR-A\SIMPR-Toki\Exe\Menu.Txt
HP-7900=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
FMV-S8235-H=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP-8300=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
VAIOZ_K=F:\SIMPR-A\SIMPR-Toki\Exe\Menu.Txt
VIRTUALXP-76997=\\tsclient\F\SIMPR-A\SIMPR-Toki\Exe\Menu.Txt
HP8300K=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP8300-1=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP-ED800-G1=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
HP-8200-NIWA=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
CDH00301=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
CDH00291=\\10.201.2.1\Application\SIM\VB\SIMPR-Toki\Exe\Menu.Txt
[Others]
LogoDisp=Yes
Logo=SIMPR-A
Demo=1
[Apparatus]
1=TX-597G
2=TX-1609
3=B-858
4=GT10Q-SR
5=ｷｰﾎﾞｰﾄﾞｲﾝﾀｰﾌｪｲｽ
6=TX-1301
7=TX-2400
[HOST]
受注データ識別=JY
保持期間=10
[Fax]
FMVD5330=Yes
Server=Server
FMV-E630=No
FMV-E620DEMO=No
FMV-W5240U=No
FMVW5220=No
FMV-D5255-PC=No
[Mail]
MailText=\\sv-cis01\Application\SIM\VB\SIMPR-CHIYODA\Exe\Mail\
MsgDir=\\sv-cis01\Application\SIM\VB\SIMPR-CHIYODA\Exe\Mail\
Mail即時送信=Y
[GT10Q-SR]
Setting=38400,N,8,2
HandShaking=0
RS232CLog=No
Use=Yes
CommPort=1
[バーコード]
JISYADEN=1
Pattern1=3,5,6,10,3
Pattern2=2,3,4,6,3
Pattern3=4,8,8,16,6
Pattern4=3,4,6,8,3
自社伝票=B0
BU=3,5,6,10,3
B0=Form設定
B1=3,5,6,10,3
B2=2,3,4,6,3
B3=4,8,8,16,6
B4=3,4,6,8,3
[ｷｰﾎﾞｰﾄﾞｲﾝﾀｰﾌｪｲｽ]
Use=Yes
[検収入力]
検収=1
[TX-597G]
Setting=9600,n,8,1
HandShaking=2
DemoFileName=DemoData.txt
DemoDir=\\sv-cis01\Application\SIM\VB\SIMPR-CHIYODA\Exe\Demo\
RS232CLog=No
CommPort=1
[Topps]
JyuDir=F:\SIMPR-A\SIMPR-CHIYODA\Exe\Topps         
JyuSaveDir=F:\SIMPR-A\SIMPR-CHIYODA\Exe\Topps\Back
JyuSaveDelDay=10
JY_TEXTID=.BAK
JY_TEXTID_Change=.OLD
JY_TEXT_Name=HSTEIKYO
SyuDir=F:\SIMPR-A\SIMPR-CHIYODA\Exe\Topps         
SyuSaveDir=F:\SIMPR-A\SIMPR-CHIYODA\Exe\Topps\Back
SyuSaveDelDay=10
[Option]
臨時かんばん=0
現品票=0
端数ラベル=0
[TX-2400]
Setting=9600,n,8,1
HandShaking=1
DemoFileName=DemoData.txt
DemoDir=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Demo\
RS232CLog=No
CommPort=1
Use=Yes
ReadAuto=No
[実績入力]
入荷=1
生産=1
[かんばん]
QRPrint=QRMaker
[TX-1609]
DemoFileName=DemoData.txt
DemoDir=\\sv-cis01\Application\SIM\VB\SIMPR-CHIYODA\Exe\Demo\
RS232CLog=No
CommPort=1
Setting=19200,n,8,1
HandShaking=0
[TX-1301]
DemoFileName=DemoData.txt
DemoDir=\\sv-cis01\Application\SIM\VB\SIMPR-Toki\Exe\Demo\
RS232CLog=No
CommPort=1
Setting=19200,n,8,1
HandShaking=0
[JText]
受注_愛知機械_ﾌｧｲﾙ名=MFDFILE*.*
受注_愛知機械_保持期間=999
受注_愛知機械_変換リスト=Yes
受注_愛知機械_変換リスト_エラー出力=Yes
受注_愛知機械_変換リスト_重複=Yes
受注_愛知機械_変換リスト_仮登録出力=Yes
受注_愛知機械_変換リスト_その他出力=Yes
出荷_テクノエイト_ﾌｧｲﾙ名=Juchu*
出荷_テクノエイト_保持期間=30
出荷_テクノエイト_変換リスト=No
出荷_テクノエイト_変換リスト_エラー出力=Yes
出荷_テクノエイト_変換リスト_重複=Yes
出荷_テクノエイト_変換リスト_仮登録出力=Yes
出荷_テクノエイト_変換リスト_その他出力=Yes
_愛知機械_ﾌｧｲﾙ名=Juchu*
_愛知機械_保持期間=30
_愛知機械_変換リスト=No
_愛知機械_変換リスト_エラー出力=Yes
_愛知機械_変換リスト_重複=Yes
_愛知機械_変換リスト_仮登録出力=Yes
_愛知機械_変換リスト_その他出力=Yes
受注_テクノエイト_ﾌｧｲﾙ名=HACHU97200*.*
受注_テクノエイト_保持期間=999
受注_テクノエイト_変換リスト=Yes
受注_テクノエイト_変換リスト_エラー出力=Yes
受注_テクノエイト_変換リスト_重複=Yes
受注_テクノエイト_変換リスト_仮登録出力=Yes
受注_テクノエイト_変換リスト_その他出力=Yes
出荷_愛知機械_ﾌｧｲﾙ名=MFDFILE*.*
出荷_愛知機械_保持期間=999
出荷_愛知機械_変換リスト=Yes
出荷_愛知機械_変換リスト_エラー出力=Yes
出荷_愛知機械_変換リスト_重複=Yes
出荷_愛知機械_変換リスト_仮登録出力=Yes
出荷_愛知機械_変換リスト_その他出力=Yes
受注_ヨロズ愛知_ﾌｧｲﾙ名=MFDFILE*.*
受注_ヨロズ愛知_保持期間=999
受注_ヨロズ愛知_変換リスト=Yes
受注_ヨロズ愛知_変換リスト_エラー出力=Yes
受注_ヨロズ愛知_変換リスト_重複=Yes
受注_ヨロズ愛知_変換リスト_仮登録出力=Yes
受注_ヨロズ愛知_変換リスト_その他出力=Yes
_ヨロズ愛知_ﾌｧｲﾙ名=MFDFILE.FIX
_ヨロズ愛知_保持期間=10
_ヨロズ愛知_変換リスト=No
_ヨロズ愛知_変換リスト_エラー出力=Yes
_ヨロズ愛知_変換リスト_重複=Yes
_ヨロズ愛知_変換リスト_仮登録出力=Yes
_ヨロズ愛知_変換リスト_その他出力=Yes
受注_トヨタ車体（順引）_ﾌｧｲﾙ名=MFDFILE.FIX
受注_トヨタ車体（順引）_保持期間=10
受注_トヨタ車体（順引）_変換リスト=No
受注_トヨタ車体（順引）_変換リスト_エラー出力=Yes
受注_トヨタ車体（順引）_変換リスト_重複=Yes
受注_トヨタ車体（順引）_変換リスト_仮登録出力=Yes
受注_トヨタ車体（順引）_変換リスト_その他出力=Yes
受注_東プレ_ﾌｧｲﾙ名=0501*.csv
受注_東プレ_保持期間=30
受注_東プレ_変換リスト=Yes
受注_東プレ_変換リスト_エラー出力=Yes
受注_東プレ_変換リスト_重複=Yes
受注_東プレ_変換リスト_仮登録出力=Yes
受注_東プレ_変換リスト_その他出力=Yes
[担当]
FMV-W5210=999
[AP26]
_ﾌｧｲﾙ名=HSTEIKYO*
_保持期間=10
_変換リスト=No
_変換リスト_エラー出力=Yes
_変換リスト_重複=Yes
_変換リスト_仮登録出力=Yes
_変換リスト_その他出力=Yes
[eKanban]
受注_ﾌｧｲﾙ格納先= 
受注_ﾌｧｲﾙ退避先=\\sv-cis01\Application\SIM\VB\SIMPR-TOKI\eKanban\Back\JY\
受注_ﾌｧｲﾙ名=HSTEIKYO*
受注_保持期間=10
受注_変換リスト=No
受注_変換リスト_エラー出力=Yes
受注_変換リスト_重複=Yes
受注_変換リスト_仮登録出力=Yes
受注_変換リスト_その他出力=Yes

[棚卸読取結果]
FLD=\\sv-cis01\Application\SIM\VB\SIMPR-TOKI\棚卸HHT読取結果\
